---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flix-database
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: ./flix-database-6.4.1.tgz
      sourceRef:
        kind: GitRepository
        name: flix-database-repo
        namespace: ${releaseNamespace}
      version: 6.4.1
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: flix-database
  valuesFrom:
    - kind: ConfigMap
      name: flix-database-6.4.1-defaults
  targetNamespace: ${releaseNamespace}
