---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flix-server-repo
  namespace: ${releaseNamespace}
spec:
  interval: 10m0s
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
