---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flix-server-repo
  namespace: ${releaseNamespace}
spec:
  interval: 10m0s
  url: https://phenderson-d2iq.github.io/flix-server-chart
  ref:
    branch: master
